# Generated by Django 5.0.3 on 2024-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_profile_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='example: Python, Java, C++'),
        ),
    ]
